/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottogui;

import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author x15015556
 */
public class LottoPhase2GUI extends javax.swing.JFrame implements ActionListener {
    
    Timer t = new Timer (1000,this);
    private int[] secretMain = new int[5];
    private int[] secretPlus1 = new int[5];
    private int[] secretPlus2 = new int[5];
    private int[][] num = new int[3][5];
    private int correctL1Main; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Main;
    private int correctL3Main;
    private int correctL1Plus1; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Plus1;
    private int correctL3Plus1;
    private int correctL1Plus2; //correctL1 (correct Line 1 -- checking if a number matches secret/result
    private int correctL2Plus2;
    private int correctL3Plus2;
    private String playingLottoPlus;
    private int[] quickPickL1 = new int[5];
    private int[] quickPickL2 = new int[5];
    private int[] quickPickL3 = new int[5];
            
    /**
     * Creates new form LottoPhase2GUI
     */
    public LottoPhase2GUI() {
        t.start();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesNoBtnGrp = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        headingLbl = new javax.swing.JLabel();
        playingPlusLbl = new javax.swing.JLabel();
        selectLbl = new javax.swing.JLabel();
        line1Lbl = new javax.swing.JLabel();
        line00Tf = new javax.swing.JTextField();
        line01Tf = new javax.swing.JTextField();
        line02Tf = new javax.swing.JTextField();
        line03Tf = new javax.swing.JTextField();
        line10Tf = new javax.swing.JTextField();
        line11Tf = new javax.swing.JTextField();
        line12Tf = new javax.swing.JTextField();
        line13Tf = new javax.swing.JTextField();
        line04Tf = new javax.swing.JTextField();
        line14Tf = new javax.swing.JTextField();
        line20Tf = new javax.swing.JTextField();
        line21Tf = new javax.swing.JTextField();
        line22Tf = new javax.swing.JTextField();
        line23Tf = new javax.swing.JTextField();
        line24Tf = new javax.swing.JTextField();
        playGameBtn = new javax.swing.JButton();
        line2Lbl = new javax.swing.JLabel();
        line3Lbl = new javax.swing.JLabel();
        plus1Results2Lbl1 = new javax.swing.JLabel();
        displayResults0Lbl = new javax.swing.JLabel();
        resultsLbl = new javax.swing.JLabel();
        resultsLbl1 = new javax.swing.JLabel();
        displayPlus1_0Lbl = new javax.swing.JLabel();
        resultsLbl2 = new javax.swing.JLabel();
        displayPlus2_0Lbl = new javax.swing.JLabel();
        lottoResultsLbl = new javax.swing.JLabel();
        matchedNumsLbl = new javax.swing.JLabel();
        matchedMainDrawLbl = new javax.swing.JLabel();
        mainMatchedTextL1Lbl = new javax.swing.JLabel();
        mainMatchedTextL3Lbl = new javax.swing.JLabel();
        mainMatchedTextL2Lbl = new javax.swing.JLabel();
        matchedMainL1Lbl = new javax.swing.JLabel();
        matchedMainL2Lbl = new javax.swing.JLabel();
        matchedMainL3Lbl = new javax.swing.JLabel();
        matchedPlus1DrawLbl = new javax.swing.JLabel();
        matchedPlus1L1Lbl = new javax.swing.JLabel();
        matchedPlus1L2Lbl = new javax.swing.JLabel();
        matchedPlus1L3Lbl = new javax.swing.JLabel();
        matchedPlus2DrawLbl = new javax.swing.JLabel();
        matchedPlus2L1Lbl = new javax.swing.JLabel();
        matchedPlus2L2Lbl = new javax.swing.JLabel();
        matchedPlus2L3Lbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        playPhase1Btn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        lottoPlusAnsLbl = new javax.swing.JLabel();
        verifyButtonPressedLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        headerPicLbl = new javax.swing.JLabel();
        yesRadioBtn = new javax.swing.JRadioButton();
        noRadioBtn = new javax.swing.JRadioButton();
        quickPickL1LBtn = new javax.swing.JButton();
        quickPickL2Lbl = new javax.swing.JButton();
        quickPickL3Btn = new javax.swing.JButton();
        duplicateLbl = new javax.swing.JLabel();
        savedNumsLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        savedNumersLbl = new javax.swing.JLabel();
        savedL1textLBL = new javax.swing.JLabel();
        savedL2textLBL = new javax.swing.JLabel();
        savedL3textLBL = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        generateBtn = new javax.swing.JButton();
        changeResultsBtn = new javax.swing.JButton();
        savedNumsDisplayL1Lbl = new javax.swing.JLabel();
        savedNumsDisplayL2Lbl = new javax.swing.JLabel();
        savedNumsDisplayL3Lbl = new javax.swing.JLabel();
        savedMessageLbl = new javax.swing.JLabel();
        savedNumbersTimeLbl = new javax.swing.JLabel();
        currentTimeLbl = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        secretNumMain1Tf = new javax.swing.JTextField();
        secretNumMain2Tf = new javax.swing.JTextField();
        secretNumMain3Tf = new javax.swing.JTextField();
        secretNumMain4Tf = new javax.swing.JTextField();
        secretNumMain5Tf = new javax.swing.JTextField();
        secretP1Num1Tf = new javax.swing.JTextField();
        secretP1Num2Tf = new javax.swing.JTextField();
        secretP1Num3Tf = new javax.swing.JTextField();
        secretP1Num4Tf = new javax.swing.JTextField();
        secretP1Num5Tf = new javax.swing.JTextField();
        secretP2Num1Tf = new javax.swing.JTextField();
        secretP2Num2Tf = new javax.swing.JTextField();
        secretP2Num3Tf = new javax.swing.JTextField();
        secretP2Num4Tf = new javax.swing.JTextField();
        secretP2Num5Tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Lucida Calligraphy", 3, 48)); // NOI18N
        titleLbl.setText("Phase 2");

        headingLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingLbl.setText("Would you like to play the Lotto Plus draws?");

        playingPlusLbl.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        playingPlusLbl.setForeground(new java.awt.Color(153, 153, 0));
        playingPlusLbl.setText("Playing Lotto Plus:");

        selectLbl.setText("Please select your numbers from 1 - 40. (Please input a number in all fields)");

        line1Lbl.setText("Line 1:");

        line00Tf.setText("0");

        line01Tf.setText("0");
        line01Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line01TfActionPerformed(evt);
            }
        });

        line02Tf.setText("0");

        line03Tf.setText("0");

        line10Tf.setText("0");

        line11Tf.setText("0");

        line12Tf.setText("0");

        line13Tf.setText("0");

        line04Tf.setText("0");

        line14Tf.setText("0");

        line20Tf.setText("0");

        line21Tf.setText("0");
        line21Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line21TfActionPerformed(evt);
            }
        });

        line22Tf.setText("0");

        line23Tf.setText("0");

        line24Tf.setText("0");

        playGameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottogui/play_full_color.png"))); // NOI18N
        playGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameBtnActionPerformed(evt);
            }
        });

        line2Lbl.setText("Line 2:");

        line3Lbl.setText("Line 3:");

        displayResults0Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        displayResults0Lbl.setForeground(new java.awt.Color(0, 204, 204));

        resultsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(0, 204, 204));
        resultsLbl.setText("Main draw:");

        resultsLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultsLbl1.setForeground(new java.awt.Color(204, 0, 204));
        resultsLbl1.setText("Plus 1 Draw:");

        displayPlus1_0Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        displayPlus1_0Lbl.setForeground(new java.awt.Color(204, 0, 204));

        resultsLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultsLbl2.setForeground(new java.awt.Color(204, 153, 0));
        resultsLbl2.setText("Plus 2 Draw:");

        displayPlus2_0Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        displayPlus2_0Lbl.setForeground(new java.awt.Color(204, 153, 0));

        lottoResultsLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lottoResultsLbl.setForeground(new java.awt.Color(255, 153, 0));
        lottoResultsLbl.setText("<html><u>Lotto Results:</u></html>");

        matchedNumsLbl.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        matchedNumsLbl.setText("Numbers Matched:");

        matchedMainDrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedMainDrawLbl.setForeground(new java.awt.Color(0, 204, 204));
        matchedMainDrawLbl.setText("Main Draw:");

        mainMatchedTextL1Lbl.setText("Numbers matched on line 1:");

        mainMatchedTextL3Lbl.setText("Numbers matched on line 3:");

        mainMatchedTextL2Lbl.setText("Numbers matched on line 2:");

        matchedMainL1Lbl.setForeground(new java.awt.Color(0, 204, 204));
        matchedMainL1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedMainL2Lbl.setForeground(new java.awt.Color(0, 204, 204));
        matchedMainL2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedMainL3Lbl.setForeground(new java.awt.Color(0, 204, 204));
        matchedMainL3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus1DrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedPlus1DrawLbl.setForeground(new java.awt.Color(204, 0, 204));
        matchedPlus1DrawLbl.setText("Lotto Plus 1:");

        matchedPlus1L1Lbl.setForeground(new java.awt.Color(204, 0, 204));
        matchedPlus1L1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus1L2Lbl.setForeground(new java.awt.Color(204, 0, 204));
        matchedPlus1L2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus1L3Lbl.setForeground(new java.awt.Color(204, 0, 204));
        matchedPlus1L3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus2DrawLbl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        matchedPlus2DrawLbl.setForeground(new java.awt.Color(204, 153, 0));
        matchedPlus2DrawLbl.setText("Lotto Plus 2:");

        matchedPlus2L1Lbl.setForeground(new java.awt.Color(204, 153, 0));
        matchedPlus2L1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus2L2Lbl.setForeground(new java.awt.Color(204, 153, 0));
        matchedPlus2L2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matchedPlus2L3Lbl.setForeground(new java.awt.Color(204, 153, 0));
        matchedPlus2L3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottogui/backBtn32x32.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        playPhase1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottogui/phase1.png"))); // NOI18N
        playPhase1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPhase1BtnActionPerformed(evt);
            }
        });

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottogui/exitBtn32x32.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        lottoPlusAnsLbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lottoPlusAnsLbl.setForeground(new java.awt.Color(153, 153, 0));

        verifyButtonPressedLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verifyButtonPressedLbl.setForeground(new java.awt.Color(255, 0, 51));

        headerPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottogui/lotto.jpg"))); // NOI18N

        yesRadioBtn.setBackground(new java.awt.Color(0, 204, 0));
        yesNoBtnGrp.add(yesRadioBtn);
        yesRadioBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        yesRadioBtn.setForeground(new java.awt.Color(255, 255, 0));
        yesRadioBtn.setText("YES");
        yesRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioBtnActionPerformed(evt);
            }
        });

        noRadioBtn.setBackground(new java.awt.Color(153, 0, 0));
        yesNoBtnGrp.add(noRadioBtn);
        noRadioBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        noRadioBtn.setForeground(new java.awt.Color(255, 255, 0));
        noRadioBtn.setText("NO");
        noRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioBtnActionPerformed(evt);
            }
        });

        quickPickL1LBtn.setText("Quick Pick");
        quickPickL1LBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickPickL1LBtnActionPerformed(evt);
            }
        });

        quickPickL2Lbl.setText("Quick Pick");
        quickPickL2Lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickPickL2LblActionPerformed(evt);
            }
        });

        quickPickL3Btn.setText("Quick Pick");
        quickPickL3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickPickL3BtnActionPerformed(evt);
            }
        });

        duplicateLbl.setForeground(new java.awt.Color(255, 0, 0));

        savedNumsLbl.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        savedNumsLbl.setForeground(new java.awt.Color(51, 204, 0));
        savedNumsLbl.setText("SAVED NUMBERS:");

        saveBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save Numbers");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        loadBtn.setBackground(new java.awt.Color(102, 102, 102));
        loadBtn.setForeground(new java.awt.Color(255, 255, 255));
        loadBtn.setText("Load numbers");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete saved numbers");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        savedNumersLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savedNumersLbl.setText("Saved Numbers:");

        savedL1textLBL.setText("Saved Line 1: ");

        savedL2textLBL.setText("Saved Line 2:");

        savedL3textLBL.setText("Saved Line 3:");

        generateBtn.setText("Generate results");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        changeResultsBtn.setText("Change results");
        changeResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResultsBtnActionPerformed(evt);
            }
        });

        savedMessageLbl.setForeground(new java.awt.Color(255, 0, 0));

        savedNumbersTimeLbl.setForeground(new java.awt.Color(51, 204, 0));

        currentTimeLbl.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        secretNumMain1Tf.setText("0");
        secretNumMain1Tf.setMaximumSize(new java.awt.Dimension(0, 0));
        secretNumMain1Tf.setMinimumSize(new java.awt.Dimension(0, 0));
        secretNumMain1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretNumMain1TfActionPerformed(evt);
            }
        });

        secretNumMain2Tf.setText("0");

        secretNumMain3Tf.setText("0");

        secretNumMain4Tf.setText("0");

        secretNumMain5Tf.setText("0");

        secretP1Num1Tf.setText("0");
        secretP1Num1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretP1Num1TfActionPerformed(evt);
            }
        });

        secretP1Num2Tf.setText("0");

        secretP1Num3Tf.setText("0");

        secretP1Num4Tf.setText("0");

        secretP1Num5Tf.setText("0");

        secretP2Num1Tf.setText("0");

        secretP2Num2Tf.setText("0");

        secretP2Num3Tf.setText("0");

        secretP2Num4Tf.setText("0");

        secretP2Num5Tf.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(selectLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(playingPlusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lottoPlusAnsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(headerPicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headingLbl)
                        .addGap(18, 18, 18)
                        .addComponent(yesRadioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(noRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line1Lbl)
                            .addComponent(line3Lbl)
                            .addComponent(line2Lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(line10Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line11Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line12Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line13Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line14Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(line20Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line21Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line22Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line23Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(line24Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quickPickL2Lbl)
                                            .addComponent(quickPickL3Btn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(line00Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line01Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line02Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line03Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line04Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quickPickL1LBtn)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(playGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savedNumsLbl)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(savedMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(secretNumMain2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(secretNumMain3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(secretNumMain4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secretNumMain5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secretP1Num2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playPhase1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(237, 237, 237)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus1Results2Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(verifyButtonPressedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mainMatchedTextL3Lbl)
                                    .addComponent(mainMatchedTextL2Lbl)
                                    .addComponent(mainMatchedTextL1Lbl))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matchedMainL2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matchedMainL1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matchedMainL3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(secretP2Num1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secretP2Num2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(secretP1Num3Tf)
                                .addGap(279, 279, 279))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matchedNumsLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(changeResultsBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(secretP1Num1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(secretP1Num5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(28, 28, 28)
                                                        .addComponent(secretP2Num4Tf)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(secretP2Num3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(secretP2Num5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(68, 68, 68))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(secretNumMain1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(secretP1Num4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savedNumersLbl)
                                    .addComponent(savedNumbersTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(savedL3textLBL)
                                            .addGap(18, 18, 18)
                                            .addComponent(savedNumsDisplayL3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(savedL2textLBL)
                                            .addGap(18, 18, 18)
                                            .addComponent(savedNumsDisplayL2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(savedL1textLBL)
                                            .addGap(18, 18, 18)
                                            .addComponent(savedNumsDisplayL1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(displayResults0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(displayPlus1_0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matchedMainDrawLbl)
                                            .addComponent(resultsLbl))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resultsLbl1)
                                            .addComponent(matchedPlus1L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus1DrawLbl)
                                            .addComponent(matchedPlus1L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus1L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayPlus2_0Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matchedPlus2DrawLbl)
                                            .addComponent(resultsLbl2)
                                            .addComponent(matchedPlus2L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus2L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus2L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duplicateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lottoResultsLbl)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(headerPicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verifyButtonPressedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLbl)
                    .addComponent(yesRadioBtn)
                    .addComponent(noRadioBtn))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playingPlusLbl)
                    .addComponent(lottoPlusAnsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duplicateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line1Lbl)
                    .addComponent(line00Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line01Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line02Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line03Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line04Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quickPickL1LBtn)
                    .addComponent(generateBtn))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(line10Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line11Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line12Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line13Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line14Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line2Lbl)
                            .addComponent(quickPickL2Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(line20Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line21Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line22Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line23Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line24Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line3Lbl)
                            .addComponent(quickPickL3Btn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(savedNumsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savedMessageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(savedNumersLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savedNumsDisplayL1Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loadBtn)
                        .addComponent(savedL1textLBL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteBtn)
                        .addComponent(savedL2textLBL))
                    .addComponent(savedNumsDisplayL2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(savedL3textLBL)
                                            .addComponent(savedNumsDisplayL3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(secretP2Num1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(secretP2Num2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(secretNumMain1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savedNumbersTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(secretP2Num5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secretP1Num3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(secretP2Num3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secretP2Num4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(secretP1Num4Tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secretP1Num5Tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(currentTimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)))
                        .addComponent(secretNumMain5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secretNumMain2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secretNumMain3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secretNumMain4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secretP1Num2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resultsLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resultsLbl)
                                    .addComponent(lottoResultsLbl)))
                            .addComponent(resultsLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(displayPlus1_0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayPlus2_0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayResults0Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(changeResultsBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plus1Results2Lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(matchedMainDrawLbl)
                                            .addComponent(matchedPlus1DrawLbl)
                                            .addComponent(matchedNumsLbl)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(matchedPlus2DrawLbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matchedMainL1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus1L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus2L1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matchedPlus1L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matchedPlus2L2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(matchedPlus2L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(matchedPlus1L3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mainMatchedTextL1Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(matchedMainL2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(matchedMainL3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mainMatchedTextL2Lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mainMatchedTextL3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playPhase1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(secretP1Num1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LottoPhase2GUI p2GUI = new LottoPhase2GUI();
        p2GUI.setVisible(false);
        dispose();
        
        LottoMainGUI mainGUI = new LottoMainGUI();
        mainGUI.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void playPhase1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPhase1BtnActionPerformed
        LottoPhase2GUI p2GUI = new LottoPhase2GUI();
        p2GUI.setVisible(false);
        dispose();
        
        LottoPhase1GUI p1GUI = new LottoPhase1GUI();
        p1GUI.setVisible(true);
    }//GEN-LAST:event_playPhase1BtnActionPerformed

    private void playGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameBtnActionPerformed
        if( (line00Tf.getText().equals("")) || (line01Tf.getText().equals("")) || (line02Tf.getText().equals("")) || (line03Tf.getText().equals("")) || (line04Tf.getText().equals("")) ||
            (line10Tf.getText().equals("")) || (line11Tf.getText().equals("")) || (line12Tf.getText().equals("")) || (line13Tf.getText().equals("")) || (line04Tf.getText().equals("")) ||            (line20Tf.getText().equals("")) || (line21Tf.getText().equals("")) || (line22Tf.getText().equals("")) || (line23Tf.getText().equals("")) || (line24Tf.getText().equals("")) ) { //This is to catch users who leaves a text field blank. 
            
            duplicateLbl.setText("Error: Empty value(s) found. Please input value(s) into all fields.");
        } 
        else{
        LottoPhase2MainDraw p2Main = new LottoPhase2MainDraw();
        
        boolean hasDuplicates = false;
        boolean outOfRange = false;
        
        duplicateLbl.setText("");
        
        num[0][0] = Integer.parseInt(line00Tf.getText());
        num[0][1] = Integer.parseInt(line01Tf.getText());
        num[0][2] = Integer.parseInt(line02Tf.getText());
        num[0][3] = Integer.parseInt(line03Tf.getText());
        num[0][4] = Integer.parseInt(line04Tf.getText());
        num[1][0] = Integer.parseInt(line10Tf.getText());
        num[1][1] = Integer.parseInt(line11Tf.getText());
        num[1][2] = Integer.parseInt(line12Tf.getText());
        num[1][3] = Integer.parseInt(line13Tf.getText());
        num[1][4] = Integer.parseInt(line14Tf.getText());
        num[2][0] = Integer.parseInt(line20Tf.getText());
        num[2][1] = Integer.parseInt(line21Tf.getText());
        num[2][2] = Integer.parseInt(line22Tf.getText());
        num[2][3] = Integer.parseInt(line23Tf.getText());
        num[2][4] = Integer.parseInt(line24Tf.getText());
        
        secretMain[0] = Integer.parseInt(secretNumMain1Tf.getText());
        secretMain[1] = Integer.parseInt(secretNumMain2Tf.getText());
        secretMain[2] = Integer.parseInt(secretNumMain3Tf.getText());
        secretMain[3] = Integer.parseInt(secretNumMain4Tf.getText());
        secretMain[4] = Integer.parseInt(secretNumMain5Tf.getText());
        
        secretPlus1[0] = Integer.parseInt(secretP1Num1Tf.getText());
        secretPlus1[1] = Integer.parseInt(secretP1Num2Tf.getText());
        secretPlus1[2] = Integer.parseInt(secretP1Num3Tf.getText());
        secretPlus1[3] = Integer.parseInt(secretP1Num4Tf.getText());
        secretPlus1[4] = Integer.parseInt(secretP1Num5Tf.getText());
        
        secretPlus2[0] = Integer.parseInt(secretP2Num1Tf.getText());
        secretPlus2[1] = Integer.parseInt(secretP2Num2Tf.getText());
        secretPlus2[2] = Integer.parseInt(secretP2Num3Tf.getText());
        secretPlus2[3] = Integer.parseInt(secretP2Num4Tf.getText());
        secretPlus2[4] = Integer.parseInt(secretP2Num5Tf.getText());
        
        
        
        playingLottoPlus = lottoPlusAnsLbl.getText();
        
        DuplicatesRange dupr = new DuplicatesRange();
        dupr.setNum(num);
        hasDuplicates = dupr.setHasDuplicates();
        outOfRange = dupr.setOutOfRange();
        
        if((hasDuplicates == true)||(outOfRange == true) || (secretMain[0] == 0)){
            duplicateLbl.setText("Error: Duplicate found, number(s) out of range, or Results not generated");
            
            displayResults0Lbl.setText("");
            displayPlus1_0Lbl.setText("");
            displayPlus2_0Lbl.setText("");

            matchedMainL1Lbl.setText("");
            matchedMainL2Lbl.setText("");
            matchedMainL3Lbl.setText("");
            
            matchedPlus1L1Lbl.setText("");
            matchedPlus1L2Lbl.setText("");
            matchedPlus1L3Lbl.setText("");
            
            matchedPlus2L1Lbl.setText("");
            matchedPlus2L2Lbl.setText("");
            matchedPlus2L3Lbl.setText("");
        }
        
        else if((hasDuplicates == false)&&(outOfRange == false)){
            
            if(playingLottoPlus.equals("<html><u>NO</u></html>")){
                verifyButtonPressedLbl.setText("");

                p2Main.setNum(num);
                p2Main.setSecret(secretMain);
                p2Main.computeCheckInput();
                correctL1Main = p2Main.getCorrectL1();
                correctL2Main = p2Main.getCorrectL2();
                correctL3Main = p2Main.getCorrectL3(); // runs Main draw

                //prints secret to output
                System.out.println("Phase 2 Main Secret: " + Arrays.toString(secretMain));
                System.out.println();

                matchedMainL1Lbl.setText(Integer.toString(correctL1Main));
                matchedMainL2Lbl.setText(Integer.toString(correctL2Main));
                matchedMainL3Lbl.setText(Integer.toString(correctL3Main)); // displays amount of matched numbers from Main Draw

                matchedPlus1L1Lbl.setText("Not played");
                matchedPlus1L2Lbl.setText("Not played");
                matchedPlus1L3Lbl.setText("Not played"); // informs user they didn't play Plus 1 draw

                matchedPlus2L1Lbl.setText("Not played");
                matchedPlus2L2Lbl.setText("Not played");
                matchedPlus2L3Lbl.setText("Not played"); // informs user they didn't play Plus 2 draw

            }

            else if(playingLottoPlus.equals("<html><u>YES</u></html>")){

                verifyButtonPressedLbl.setText("");

                p2Main.setNum(num);
                p2Main.setSecret(secretMain);
                p2Main.computeCheckInput();
                correctL1Main = p2Main.getCorrectL1();
                correctL2Main = p2Main.getCorrectL2();
                correctL3Main = p2Main.getCorrectL3(); // runs Main draw

                //prints secret to output
                System.out.println("Phase 2 Main Secret: " + Arrays.toString(secretMain));


                matchedMainL1Lbl.setText(Integer.toString(correctL1Main));
                matchedMainL2Lbl.setText(Integer.toString(correctL2Main));
                matchedMainL3Lbl.setText(Integer.toString(correctL3Main));

                LottoPhase2Plus1 p2Plus1 = new LottoPhase2Plus1();
                p2Plus1.setNum(num);
                p2Plus1.setSecret(secretPlus1);
                p2Plus1.computeCheckInputP1();
                correctL1Plus1 = p2Plus1.getCorrectL1();
                correctL2Plus1 = p2Plus1.getCorrectL2();
                correctL3Plus1 = p2Plus1.getCorrectL3(); //runs Plus 1 Draw

                //prints secret to output
                System.out.println("Phase 2 Plus 1 Secret: " + Arrays.toString(secretPlus1));

                matchedPlus1L1Lbl.setText(Integer.toString(correctL1Plus1));
                matchedPlus1L2Lbl.setText(Integer.toString(correctL2Plus1));
                matchedPlus1L3Lbl.setText(Integer.toString(correctL3Plus1)); // displays amount of matched numbers from Plus 1 Draw


                LottoPhase2Plus2 p2Plus2 = new LottoPhase2Plus2();
                p2Plus2.setNum(num);
                p2Plus2.setSecret(secretPlus2);
                p2Plus2.computeCheckInputP2();
                correctL1Plus2 = p2Plus2.getCorrectL1();
                correctL2Plus2 = p2Plus2.getCorrectL2();
                correctL3Plus2 = p2Plus2.getCorrectL3(); //runs Plus 2 Draw

                //prints secret to output
                System.out.println("Phase 2 Plus 2 Secret: " + Arrays.toString(secretPlus2));
                System.out.println();

                displayPlus2_0Lbl.setText(Integer.toString(secretPlus2[0]) + ", " + Integer.toString(secretPlus2[1]) + ", " + Integer.toString(secretPlus2[2]) + ", " + Integer.toString(secretPlus2[3]) + ", " + Integer.toString(secretPlus2[4]));

                matchedPlus2L1Lbl.setText(Integer.toString(correctL1Plus2));
                matchedPlus2L2Lbl.setText(Integer.toString(correctL2Plus2));
                matchedPlus2L3Lbl.setText(Integer.toString(correctL3Plus2)); // displays amount of matched numbers from Plus 2 Dra
            }

            else{
                verifyButtonPressedLbl.setText("**PLEASE MAKE A SELECTION**");
            }
        }
        }
    }//GEN-LAST:event_playGameBtnActionPerformed

    private void yesRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioBtnActionPerformed
        lottoPlusAnsLbl.setText("<html><u>YES</u></html>");
    }//GEN-LAST:event_yesRadioBtnActionPerformed

    private void noRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioBtnActionPerformed
        lottoPlusAnsLbl.setText("<html><u>NO</u></html>");
    }//GEN-LAST:event_noRadioBtnActionPerformed

    private void quickPickL1LBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickPickL1LBtnActionPerformed
        quickPickL1 = new Random().ints(1, 40).distinct().limit(5).toArray();
        
        line00Tf.setText(Integer.toString(quickPickL1[0]));
        line01Tf.setText(Integer.toString(quickPickL1[1]));
        line02Tf.setText(Integer.toString(quickPickL1[2]));
        line03Tf.setText(Integer.toString(quickPickL1[3]));
        line04Tf.setText(Integer.toString(quickPickL1[4]));

    }//GEN-LAST:event_quickPickL1LBtnActionPerformed

    private void quickPickL2LblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickPickL2LblActionPerformed
        quickPickL2 = new Random().ints(1, 40).distinct().limit(5).toArray();
        
        line10Tf.setText(Integer.toString(quickPickL2[0]));
        line11Tf.setText(Integer.toString(quickPickL2[1]));
        line12Tf.setText(Integer.toString(quickPickL2[2]));
        line13Tf.setText(Integer.toString(quickPickL2[3]));
        line14Tf.setText(Integer.toString(quickPickL2[4]));
    }//GEN-LAST:event_quickPickL2LblActionPerformed

    private void quickPickL3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickPickL3BtnActionPerformed
        quickPickL3 = new Random().ints(1, 40).distinct().limit(5).toArray();
        
        line20Tf.setText(Integer.toString(quickPickL3[0]));
        line21Tf.setText(Integer.toString(quickPickL3[1]));
        line22Tf.setText(Integer.toString(quickPickL3[2]));
        line23Tf.setText(Integer.toString(quickPickL3[3]));
        line24Tf.setText(Integer.toString(quickPickL3[4]));
    }//GEN-LAST:event_quickPickL3BtnActionPerformed

    private void line01TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line01TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line01TfActionPerformed

    private void line21TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line21TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line21TfActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        savedMessageLbl.setText("");
        
                
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm.ss");
        LocalDateTime now = LocalDateTime.now();
//        System.out.println(dtf.format(now));

        num[0][0] = Integer.parseInt(line00Tf.getText());
        num[0][1] = Integer.parseInt(line01Tf.getText());
        num[0][2] = Integer.parseInt(line02Tf.getText());
        num[0][3] = Integer.parseInt(line03Tf.getText());
        num[0][4] = Integer.parseInt(line04Tf.getText());
        num[1][0] = Integer.parseInt(line10Tf.getText());
        num[1][1] = Integer.parseInt(line11Tf.getText());
        num[1][2] = Integer.parseInt(line12Tf.getText());
        num[1][3] = Integer.parseInt(line13Tf.getText());
        num[1][4] = Integer.parseInt(line14Tf.getText());
        num[2][0] = Integer.parseInt(line20Tf.getText());
        num[2][1] = Integer.parseInt(line21Tf.getText());
        num[2][2] = Integer.parseInt(line22Tf.getText());
        num[2][3] = Integer.parseInt(line23Tf.getText());
        num[2][4] = Integer.parseInt(line24Tf.getText());
        
        if((num[0][0] == 0)|| (num[1][0] == 0) || (num[2][2] == 0)){
            savedMessageLbl.setText("Please ensure all numbers are entered before saving!");
        }
        else{
        savedNumsDisplayL1Lbl.setText(Integer.toString(num[0][0]) + ", " + Integer.toString(num[0][1]) + ", " + Integer.toString(num[0][2]) + ", " + Integer.toString(num[0][3]) + ", " + Integer.toString(num[0][4]));
        savedNumsDisplayL2Lbl.setText(Integer.toString(num[1][0]) + ", " + Integer.toString(num[1][1]) + ", " + Integer.toString(num[1][2]) + ", " + Integer.toString(num[1][3]) + ", " + Integer.toString(num[1][4]));
        savedNumsDisplayL3Lbl.setText(Integer.toString(num[2][0]) + ", " + Integer.toString(num[2][1]) + ", " + Integer.toString(num[2][2]) + ", " + Integer.toString(num[2][3]) + ", " + Integer.toString(num[2][4]));
        
        savedNumbersTimeLbl.setText("Successfully saved numbers at " + dtf.format(now));
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try {
            outFile = new File("savedNumbersPhase2.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(num);

            savedMessageLbl.setText("Numbers saved!");

            oStream.close();
            
        } 
        catch (IOException e) {
            System.out.println("Error: " + e);
        }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        savedMessageLbl.setText("");
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream; 
        
        try{
            inFile = new File("savedNumbersPhase2.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            if (inFile.exists()) {
                num = (int[][]) oStream.readObject();

                line00Tf.setText(Integer.toString(num[0][0]));
                line01Tf.setText(Integer.toString(num[0][1]));
                line02Tf.setText(Integer.toString(num[0][2]));
                line03Tf.setText(Integer.toString(num[0][3]));
                line04Tf.setText(Integer.toString(num[0][4])); //Line 1
                
                line10Tf.setText(Integer.toString(num[1][0]));
                line11Tf.setText(Integer.toString(num[1][1]));
                line12Tf.setText(Integer.toString(num[1][2]));
                line13Tf.setText(Integer.toString(num[1][3])); //Line 2
                line14Tf.setText(Integer.toString(num[1][4]));
                
                line20Tf.setText(Integer.toString(num[2][0]));
                line21Tf.setText(Integer.toString(num[2][1]));
                line22Tf.setText(Integer.toString(num[2][2]));
                line23Tf.setText(Integer.toString(num[2][3]));
                line24Tf.setText(Integer.toString(num[2][4])); //Line 3
                
                savedNumsDisplayL1Lbl.setText(Integer.toString(num[0][0]) + ", " + Integer.toString(num[0][1]) + ", " + Integer.toString(num[0][2]) + ", " + Integer.toString(num[0][3]) + ", " + Integer.toString(num[0][4]));
                savedNumsDisplayL2Lbl.setText(Integer.toString(num[1][0]) + ", " + Integer.toString(num[1][1]) + ", " + Integer.toString(num[1][2]) + ", " + Integer.toString(num[1][3]) + ", " + Integer.toString(num[1][4]));
                savedNumsDisplayL3Lbl.setText(Integer.toString(num[2][0]) + ", " + Integer.toString(num[2][1]) + ", " + Integer.toString(num[2][2]) + ", " + Integer.toString(num[2][3]) + ", " + Integer.toString(num[2][4]));
                
            }
            oStream.close();
        }
        catch(IOException e){
            savedNumsDisplayL1Lbl.setText("");
            savedNumsDisplayL2Lbl.setText("");
            savedNumsDisplayL3Lbl.setText("");
            
            savedMessageLbl.setText("No numbers saved!");

        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        savedMessageLbl.setText("");
       
            File savedNums = new File("savedNumbersPhase2.data");
            if (savedNums.exists()) {
                savedNums.delete();

                savedMessageLbl.setText("Saved numbers deleted!");
            }
            else{
                savedMessageLbl.setText("No saved numbers to delete!");
            }

            savedNumsDisplayL1Lbl.setText("");
            savedNumsDisplayL2Lbl.setText("");
            savedNumsDisplayL3Lbl.setText("");
            savedNumbersTimeLbl.setText("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void secretNumMain1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretNumMain1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secretNumMain1TfActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
//            for(int i = 0; i<5; i++){ 
                secretMain = new Random().ints(1, 40).distinct().limit(5).toArray();
//            }

            secretNumMain1Tf.setText(Integer.toString(secretMain[0]));
            secretNumMain2Tf.setText(Integer.toString(secretMain[1]));
            secretNumMain3Tf.setText(Integer.toString(secretMain[2]));
            secretNumMain4Tf.setText(Integer.toString(secretMain[3]));
            secretNumMain5Tf.setText(Integer.toString(secretMain[4]));

            displayResults0Lbl.setText(Integer.toString(secretMain[0]) + ", " + Integer.toString(secretMain[1]) + ", " + Integer.toString(secretMain[2]) + ", " + Integer.toString(secretMain[3]) + ", " + Integer.toString(secretMain[4]));
            
//            for(int j = 0; j<secretPlus1.length; j++){ 
                secretPlus1 = new Random().ints(1, 40).distinct().limit(5).toArray();
//            }
            
            secretP1Num1Tf.setText(Integer.toString(secretPlus1[0]));
            secretP1Num2Tf.setText(Integer.toString(secretPlus1[1]));
            secretP1Num2Tf.setText(Integer.toString(secretPlus1[2]));
            secretP1Num4Tf.setText(Integer.toString(secretPlus1[3]));
            secretP1Num5Tf.setText(Integer.toString(secretPlus1[4]));
            
            displayPlus1_0Lbl.setText(Integer.toString(secretPlus1[0]) + ", " + Integer.toString(secretPlus1[1]) + ", " + Integer.toString(secretPlus1[2]) + ", " + Integer.toString(secretPlus1[3]) + ", " + Integer.toString(secretPlus1[4]));
            
//            for(int k = 0; k<5; k++){
            secretPlus2 = new Random().ints(1, 40).distinct().limit(5).toArray();
//            }
            
            secretP2Num1Tf.setText(Integer.toString(secretPlus2[0]));
            secretP2Num2Tf.setText(Integer.toString(secretPlus2[1]));
            secretP2Num2Tf.setText(Integer.toString(secretPlus2[2]));
            secretP2Num4Tf.setText(Integer.toString(secretPlus2[3]));
            secretP2Num5Tf.setText(Integer.toString(secretPlus2[4]));
            
            displayPlus2_0Lbl.setText(Integer.toString(secretPlus2[0]) + ", " + Integer.toString(secretPlus2[1]) + ", " + Integer.toString(secretPlus2[2]) + ", " + Integer.toString(secretPlus2[3]) + ", " + Integer.toString(secretPlus2[4]));
    }//GEN-LAST:event_generateBtnActionPerformed
    
    private void secretP1Num1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretP1Num1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secretP1Num1TfActionPerformed

    private void changeResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResultsBtnActionPerformed
        for(int i = 0; i<secretMain.length; i++){
            secretMain = new Random().ints(1, 40).distinct().limit(5).toArray();
        }

        secretNumMain1Tf.setText(Integer.toString(secretMain[0]));
        secretNumMain2Tf.setText(Integer.toString(secretMain[1]));
        secretNumMain3Tf.setText(Integer.toString(secretMain[2]));
        secretNumMain4Tf.setText(Integer.toString(secretMain[3]));
        secretNumMain5Tf.setText(Integer.toString(secretMain[4]));

        displayResults0Lbl.setText(Integer.toString(secretMain[0]) + ", " + Integer.toString(secretMain[1]) + ", " + Integer.toString(secretMain[2]) + ", " + Integer.toString(secretMain[3]) + ", " + Integer.toString(secretMain[4]));

        for(int j = 0; j<secretPlus1.length; j++){
            secretPlus1 = new Random().ints(1, 40).distinct().limit(5).toArray();
        }

        secretP1Num1Tf.setText(Integer.toString(secretPlus1[0]));
        secretP1Num2Tf.setText(Integer.toString(secretPlus1[1]));
        secretP1Num2Tf.setText(Integer.toString(secretPlus1[2]));
        secretP1Num4Tf.setText(Integer.toString(secretPlus1[3]));
        secretP1Num5Tf.setText(Integer.toString(secretPlus1[4]));

        displayPlus1_0Lbl.setText(Integer.toString(secretPlus1[0]) + ", " + Integer.toString(secretPlus1[1]) + ", " + Integer.toString(secretPlus1[2]) + ", " + Integer.toString(secretPlus1[3]) + ", " + Integer.toString(secretPlus1[4]));

        for(int k = 0; k<secretPlus2.length; k++){
            secretPlus2 = new Random().ints(1, 40).distinct().limit(5).toArray();
        }

        secretP2Num1Tf.setText(Integer.toString(secretPlus2[0]));
        secretP2Num2Tf.setText(Integer.toString(secretPlus2[1]));
        secretP2Num2Tf.setText(Integer.toString(secretPlus2[2]));
        secretP2Num4Tf.setText(Integer.toString(secretPlus2[3]));
        secretP2Num5Tf.setText(Integer.toString(secretPlus2[4]));

        displayPlus2_0Lbl.setText(Integer.toString(secretPlus2[0]) + ", " + Integer.toString(secretPlus2[1]) + ", " + Integer.toString(secretPlus2[2]) + ", " + Integer.toString(secretPlus2[3]) + ", " + Integer.toString(secretPlus2[4]));
    }//GEN-LAST:event_changeResultsBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("H:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        currentTimeLbl.setText("Current time: " + dtf.format(now));
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        Button refresh = new Button();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoPhase2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LottoPhase2GUI().setVisible(true);
        });
    }
        public void actionPerformed (ActionEvent e){
        if(e.getSource() == t){
            refreshBtn.doClick();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changeResultsBtn;
    private javax.swing.JLabel currentTimeLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel displayPlus1_0Lbl;
    private javax.swing.JLabel displayPlus2_0Lbl;
    private javax.swing.JLabel displayResults0Lbl;
    private javax.swing.JLabel duplicateLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel headerPicLbl;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField line00Tf;
    private javax.swing.JTextField line01Tf;
    private javax.swing.JTextField line02Tf;
    private javax.swing.JTextField line03Tf;
    private javax.swing.JTextField line04Tf;
    private javax.swing.JTextField line10Tf;
    private javax.swing.JTextField line11Tf;
    private javax.swing.JTextField line12Tf;
    private javax.swing.JTextField line13Tf;
    private javax.swing.JTextField line14Tf;
    private javax.swing.JLabel line1Lbl;
    private javax.swing.JTextField line20Tf;
    private javax.swing.JTextField line21Tf;
    private javax.swing.JTextField line22Tf;
    private javax.swing.JTextField line23Tf;
    private javax.swing.JTextField line24Tf;
    private javax.swing.JLabel line2Lbl;
    private javax.swing.JLabel line3Lbl;
    private javax.swing.JButton loadBtn;
    private javax.swing.JLabel lottoPlusAnsLbl;
    private javax.swing.JLabel lottoResultsLbl;
    private javax.swing.JLabel mainMatchedTextL1Lbl;
    private javax.swing.JLabel mainMatchedTextL2Lbl;
    private javax.swing.JLabel mainMatchedTextL3Lbl;
    private javax.swing.JLabel matchedMainDrawLbl;
    private javax.swing.JLabel matchedMainL1Lbl;
    private javax.swing.JLabel matchedMainL2Lbl;
    private javax.swing.JLabel matchedMainL3Lbl;
    private javax.swing.JLabel matchedNumsLbl;
    private javax.swing.JLabel matchedPlus1DrawLbl;
    private javax.swing.JLabel matchedPlus1L1Lbl;
    private javax.swing.JLabel matchedPlus1L2Lbl;
    private javax.swing.JLabel matchedPlus1L3Lbl;
    private javax.swing.JLabel matchedPlus2DrawLbl;
    private javax.swing.JLabel matchedPlus2L1Lbl;
    private javax.swing.JLabel matchedPlus2L2Lbl;
    private javax.swing.JLabel matchedPlus2L3Lbl;
    private javax.swing.JRadioButton noRadioBtn;
    private javax.swing.JButton playGameBtn;
    private javax.swing.JButton playPhase1Btn;
    private javax.swing.JLabel playingPlusLbl;
    private javax.swing.JLabel plus1Results2Lbl1;
    private javax.swing.JButton quickPickL1LBtn;
    private javax.swing.JButton quickPickL2Lbl;
    private javax.swing.JButton quickPickL3Btn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JLabel resultsLbl1;
    private javax.swing.JLabel resultsLbl2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel savedL1textLBL;
    private javax.swing.JLabel savedL2textLBL;
    private javax.swing.JLabel savedL3textLBL;
    private javax.swing.JLabel savedMessageLbl;
    private javax.swing.JLabel savedNumbersTimeLbl;
    private javax.swing.JLabel savedNumersLbl;
    private javax.swing.JLabel savedNumsDisplayL1Lbl;
    private javax.swing.JLabel savedNumsDisplayL2Lbl;
    private javax.swing.JLabel savedNumsDisplayL3Lbl;
    private javax.swing.JLabel savedNumsLbl;
    private javax.swing.JTextField secretNumMain1Tf;
    private javax.swing.JTextField secretNumMain2Tf;
    private javax.swing.JTextField secretNumMain3Tf;
    private javax.swing.JTextField secretNumMain4Tf;
    private javax.swing.JTextField secretNumMain5Tf;
    private javax.swing.JTextField secretP1Num1Tf;
    private javax.swing.JTextField secretP1Num2Tf;
    private javax.swing.JTextField secretP1Num3Tf;
    private javax.swing.JTextField secretP1Num4Tf;
    private javax.swing.JTextField secretP1Num5Tf;
    private javax.swing.JTextField secretP2Num1Tf;
    private javax.swing.JTextField secretP2Num2Tf;
    private javax.swing.JTextField secretP2Num3Tf;
    private javax.swing.JTextField secretP2Num4Tf;
    private javax.swing.JTextField secretP2Num5Tf;
    private javax.swing.JLabel selectLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel verifyButtonPressedLbl;
    private javax.swing.ButtonGroup yesNoBtnGrp;
    private javax.swing.JRadioButton yesRadioBtn;
    // End of variables declaration//GEN-END:variables
}
